# -*- coding: utf-8 -*-
"""PDF_to_Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGkxvhKBepHPvoDkkZMIvIH6iHf9FIni
"""

# Install required libraries
!apt-get install -y poppler-utils
!pip install pdf2image

import os
from pdf2image import convert_from_path

# Set the PDF file path
pdf_path = "/content/[MAIN] AL ADABUL MUFRAD- NASIRUDDIN PART 1 (1).pdf"

# Convert PDF pages to images
images = convert_from_path(pdf_path, dpi=300)

# Create an output directory for images
output_folder = "/content/pdf_images"
os.makedirs(output_folder, exist_ok=True)

# Save each page as an image
for i, image in enumerate(images):
    image_path = os.path.join(output_folder, f"page_{i+1}.png")
    image.save(image_path, "PNG")

print(f"PDF successfully converted into {len(images)} images!")